### ISSUE TITLE
Suggestion: A gif/img of the bubble chart in Readme

### ISSUE THREAD

**Issue by amrrs** [AashitaK/bubbly#1]
While it's fairly okay to assume that people come here knowing what a bubble chart is. Still a thought that having a gif/image of Bubble chart (even, animated) like you got in Kernel could help.

**Comment by AashitaK** [comment]
Thanks @amrrs for the suggestion. It was in my mind to add a gif/image to demonstrate the charts that bubbly can built. I will do it as soon as I can get to it. Thanks again.

**Comment by amrrs** [comment]
Thanks!

**Comment by shirinsamani** [comment]
Aashitak, thanks for sharing Bubbly. I used it recently, and it is amazing :) 
It works perfectly, except for one issue. I have categorical color_column, and I noticed the colors of items in the legend are being repeated. I could not figure it out, and I am so very thankful if you can help me with that issue.
